---
title: "Semester Project"
author: "Shelby Golden"
date: "`r Sys.Date()`"
always_allow_html: yes
output: pdf_document
---

```{r setup, include=FALSE}
## Setup
knitr::opts_chunk$set(echo = TRUE)

library("rmarkdown")
#library("devtools")
library("githubinstall")
library("dplyr")
library("tidyverse")
library("ggplot2")
library("reshape")
library("ggprism")
library("gridExtra")
library("stringr")
library("lemon")
library("DiagrammeR")
library("webshot")
webshot::install_phantomjs(force = TRUE)
# githubinstall("plspm")
library("plspm")
# install.packages("devtools")
library("devtools")
# install_github("gastonstat/plspm")
library("plspm")


"%!in%" <- function(x,y)!('%in%'(x,y))
  # https://stackoverflow.com/questions/5831794/opposite-of-in-exclude-rows-with-values-specified-in-a-vector


###################################
pressure <- read.csv("/Users/melanie_goldman/Documents/Johns Hopkins University/Theory of Statistics I/Project/heart.csv")
  
# SEQN = Respondent sequence number
# ALQ101 = Had at least 12 alcohol drinks/1 yr?             - #1
# ALQ110 = Had at least 12 alcohol drinks/lifetime?
# ALQ130 = Avg # alcoholic drinks/day - past 12 mos
# SMQ020 = Smoked at least 100 cigarettes in life
# RIAGENDR = Gender                                         - #2
# HIQ210 = Time when no insurance in past year?             - #6


# Remove respondent number
pressure1 <- pressure[, names(pressure) %!in% c("SEQN")]
  
# Removed census data                                       - #3
pressure1 <- pressure1[, names(pressure1) %!in% c("RIDRETH1", "DMDCITZN", "DMDEDUC2", "DMDMARTL", "DMDHHSIZ", "WTINT2YR", "SDMVPSU", "SDMVSTRA", "INDFMPIR")]

# Removed categorical data
pressure1 <- pressure1[, names(pressure1) %!in% c("ALQ101", "ALQ110", "ALQ130", "SMQ020", "HIQ210")]

# RIDAGEYR = Age in years at screening                      - #2

# BPXSY1 = Systolic: Blood pressure (1st reading) mmHg      - #4
# BPXDI1 = Diastolic: Blood pressure (1st reading) mmHg
# BPXSY2 = Systolic: Blood pressure (2nd reading) mmHg
# BPXDI2 = Diastolic: Blood pressure (2nd reading) mmHg

# BMXWT = Weight (kg)                                       - #5
# BMXHT = Standing Height (cm)
# BMXBMI = Body Mass Index (kg/m**2)
# BMXLEG = Upper Leg Length (cm)
# BMXARML = Upper Arm Length (cm)
# BMXARMC = Arm Circumference (cm)
# BMXWAIST = Waist Circumference (cm)
  
```


```{r models, include=FALSE}
overFit = DiagrammeR("
  graph LR
    BMXWT --> Obesity
    BMXHT --> Obesity
    BMXBMI --> Obesity
    BMXLEG --> Obesity
    BMXARML --> Obesity
    BMXARMC --> Obesity
    BMXWAIST --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")

model1 = DiagrammeR("
  graph LR
    BMXWT --> Obesity
    BMXHT --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")

model2 = DiagrammeR("
  graph LR
    BMXBMI --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")

model3 = DiagrammeR("
  graph LR
    BMXLEG --> Obesity
    BMXARML --> Obesity
    BMXARMC --> Obesity
    BMXWAIST --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")

model4 = DiagrammeR("
  graph LR
    BMXWT --> Obesity
    BMXHT --> Obesity
    BMXBMI --> Obesity
    BMXLEG --> Obesity
    BMXARML --> Obesity
    BMXARMC --> Obesity
    BMXWAIST --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
")

model5 = DiagrammeR("
  graph LR
    BMXWT --> Obesity
    BMXHT --> Obesity
    BMXBMI --> Obesity
    BMXLEG --> Obesity
    BMXARML --> Obesity
    BMXARMC --> Obesity
    BMXWAIST --> Obesity
    
    Obesity --> Hypertension
    
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")
```

```{r plot, width = 60}
overFit
model1
model2
model3
model4
model5
```
```{r selection criteria function}
selection <- function(model_R, model_Q, saturated, n, predictors){
  pk = 13 + 1 #predictors + 1
  SSE = (1 - sum(model_R$inner_summary$R2))*(n - 1)
  MSE = 1 - sum(saturated$inner_summary$R2)
  
  ## PLS selection criteria
  Rsq       = sum(model_R$inner_summary$R2)
  Qsq       = sum(model_Q$inner_summary$R2)
  AdjRsq    = 1 - ( ((n - 1)/(n - pk))*(SSE/(n - 1)) )
  GoF       = model_R$gof
  
  ## Distance based criteria
  FPE       = (SSE/(n - pk))*(1 + (pk/n))
  Mallows   = (SSE/MSE) - (n - pk)
  AIC       = n*(log(SSE/n) + ((2*pk)/n))
  AICu      = n*(log(SSE/(n - pk)) + ((2*pk)/n))
  AICc      = n*(log(SSE/(n)) + ((n + pk)/(n - pk - 2)))
  
  ## Consistent criteria
  BIC       = n*(log(SSE/n) + ((pk*log(n))/n))
  GM        = (SSE/MSE) + (pk*log(n))
  HQ        = n*(log(SSE/n) + ((2*pk*log(log(n)) )/n) )
  HQc       = n*(log(SSE/n) + ((2*pk*log(log(n)) )/(n - pk - 2)) )
  
  
  ## Compile
  result <- data.frame("Type" = c(rep("PLS selection", 4), 
                                  rep("Distance based", 5), 
                                  rep("Consistent criteria", 4)),
                        "Criteria" = c("Rsq", "Qsq", "AdjRsq", "GoF",
                                       "FPE", "Mallows", "AIC", "AICu", "AICc",
                                       "BIC", "GM", "HQ", "HQc"),
                       "Result" = c(Rsq, Qsq, AdjRsq, GoF,
                                    FPE, Mallows, AIC, AICu, AICc,
                                    BIC, GM, HQ, HQc))
  
  result
}
```

```{r preperation}
# removes rows where any value has an NA
  

RIDAGEYR_dist = table(data[, 1])/nrow(data)
barplot(RIDAGEYR_dist, border = NA, main = colnames(data)[1])

BPXSY1_dist = table(data[, 2])/nrow(data)
barplot(BPXSY1_dist, border = NA, main = colnames(data)[2])

BPXDI1_dist = table(data[, 3])/nrow(data)
barplot(BPXDI1_dist, border = NA, main = colnames(data)[3])

BPXSY2_dist = table(data[, 4])/nrow(data)
barplot(BPXSY2_dist, border = NA, main = colnames(data)[4])

BPXDI2_dist = table(data[, 5])/nrow(data)
barplot(BPXDI2_dist, border = NA, main = colnames(data)[5])


```


```{r plsSetup}
Inner = DiagrammeR("
  graph LR
    Obesity --> Hypertension
")



data <- na.omit(pressure1)
# data <- data[, names(data) %!in% c("BPXDI1", "BMXHT")]
rand <- sample(1:nrow(data), 50, replace = FALSE)
data <- data[rand, ]


# Add the training data indicators for comparison of R^2 and Q^2
data$train <- rep(FALSE, nrow(data))
data$train[sample(1:nrow(data), 0.3*nrow(data))] <- TRUE
  # NOTE: must select more than the quantity of predictors


Gender        <- c(0,0,0,0)
Age           <- c(0,0,0,0)
Obesity       <- c(0,0,0,0)
Hypertension  <- c(1,1,1,0)

inner_path = rbind(Gender, Age, Obesity, Hypertension)
colnames(inner_path) = rownames(inner_path)
  # means that column j affects row i
  # therefore, obesity affects hypertension

innerplot(inner_path)

association_blocks = list(1, 2, 7:13, 3:6)
  # List 1: obesity
  # List 2: hypertension

modes = c("A", "A", "A", "B")
  # Explicitly sets the mode to be reflective
  # Explanation on PDF pg. 59


trainingData <- data[which(data$train == TRUE), ]
remainingData <- data[which(data$train != TRUE), ]

plsmodelR = plspm(trainingData, inner_path, association_blocks, modes = modes)
plsmodelQ = plspm(remainingData, inner_path, association_blocks, modes = modes)

summary(plsmodel)
plsmodel$inner_summary


## couple of good graphics
plot(plsmodel)
plot(plsmodel, what = "loadings")


## cross-loadings  - pg. 78-79
xloads = melt(plsmodel$crossloadings, id.vars = c("name", "block"),
          variable_name = "LV")

ggplot(data = xloads, aes(x = name, y = value, fill = block)) +
  geom_hline(yintercept = 0, color = "gray75") +
  geom_hline(yintercept = 0.5, color = "gray70", linetype = 2) +
  geom_bar(stat = 'identity', position = 'dodge') +
  facet_wrap(block ~ LV) +
  theme(axis.text.x = element_text(angle = 90),
        line = element_blank(),
        plot.title = element_text(size = 12)) +
  ggtitle("Crossloadings")
    ## Plot shows that there are no "traitor indicators"


## criteria
selection(plsmodelR, plsmodelQ, plsmodelR, nrow(trainingData), 13)



###################################################################
# Model 2
outter2 = DiagrammeR("
  graph LR
    BMXBMI --> Obesity
    
    Hypertension --> BPXSY1
    Hypertension --> BPXDI1
    Hypertension --> BPXSY2
    Hypertension --> BPXDI2
")




```

\newpage
## Appendix

Download: 
Info: https://towardsdatascience.com/heart-disease-classification-project-part-i-eee6301121bf

Reference:
Info: https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPX_I.htm

1. https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/ALQ_H.htm
2. https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/UMS_H.htm
3. https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/DEMO_H.htm
4. https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPX_I.htm
5. https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BMX_I.htm
6. https://wwwn.cdc.gov/nchs/nhanes/2003-2004/HIQ_C.htm

Qsqrd: https://stats.stackexchange.com/questions/292673/validation-metrics-r2-and-q2-for-partial-least-squares-pls-regression

```{r get-labels, echo = FALSE}
labs = c("setup", "models")
```

```{r all-code, ref.label = labs, eval=FALSE}
```
